// components/icons.tsx
import {
  User,
  Notebook,
  Loader2,
  Plus,
  Trash,
  Pencil,
  Save,
  X,
  Info,
  Check,
  ChevronDown,
  ChevronUp,
  Search,
  Upload,
  Image as ImageIcon,
  RefreshCcw,
  RefreshCw,
  ExternalLink,
  Package,
  ShoppingBag,
  TrendingUp,
  TrendingDown,
  Minus,
  LineChart,
  BarChart3,
  Wallet,
  Zap,
  Menu,
  Brain,
  Activity,
  HelpCircle,
  Sparkles,
  Shield,
  Settings,
  CreditCard,
  ArrowRight,
  WalletCards,
  BadgeDollarSign,
  ScanSearch,
  Trophy,
  Building2,
  Play,

  // ✅ AJOUTS pour la page Contact
  LifeBuoy,
  Database,
  Send,
  AlertTriangle,
  Link as LinkIcon,
  Bug,
  FileText,
  Scale,
} from "lucide-react"

export const Icons = {
  // Trading / Data / Market Intelligence
  trendingUp: TrendingUp,
  trendingDown: TrendingDown,
  linechart: LineChart,
  barChart3: BarChart3,
  wallet: Wallet,
  zap: Zap,
  activity: Activity,

  // Core UI
  user: User,
  note: Notebook,
  spinner: Loader2,
  add: Plus,
  delete: Trash,
  edit: Pencil,
  save: Save,
  close: X,
  check: Check,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  search: Search,
  upload: Upload,
  image: ImageIcon,
  refresh: RefreshCcw,
  refreshCw: RefreshCw,
  external: ExternalLink,
  package: Package,
  bag: ShoppingBag,
  info: Info,
  minus: Minus,
  menu: Menu,
  brain: Brain,
  helpCircle: HelpCircle,
  sparkles: Sparkles,
  shield: Shield,
  settings: Settings,
  creditCard: CreditCard,
  loader: Loader2,
  arrowRight: ArrowRight,
  walletCards: WalletCards,
  badgeDollarSign: BadgeDollarSign,
  scanSearch: ScanSearch,
  trophy: Trophy,
  building2: Building2,
  play: Play,

  // ✅ Contact page
  lifeBuoy: LifeBuoy,
  database: Database,
  send: Send,
  alertTriangle: AlertTriangle,
  link: LinkIcon,
  bug: Bug,
  fileText: FileText,
  scale: Scale,
}
